### Eager Execution

In the past tutorials [Intro-To-TF-Part1](https://github.com/Praneet460/MLCC/blob/master/Day1/Intro-To-TF-Part1.ipynb), [Intro-To-TF-Part2](https://github.com/Praneet460/MLCC/blob/master/Day2/Intro-To-TF-Part2.ipynb), [Intro-To-TF-Part3](https://github.com/Praneet460/MLCC/blob/master/Day3/Intro-To-TF-Part3.ipynb), and [Intro-To-TF-Part4](https://github.com/Praneet460/MLCC/blob/master/Day4/Intro-To-TF-Part4.ipynb), we use ```session.run()``` <i>Symbolic/ Deferred</i> execution command to display the result as output. But today we will see a new technique called <b>Eager Execution</b> to perform the same result.

<b>Eager Execution</b> is an experimental interface to TensorFlow that provides an imperative programming style. When you enable ```Eager execution```, TensorFlow operations execute immediately as they are called from Python. That means you do not execute a pre-constructed graph with ```Session.run()```. This allows for fast debugging and a more intuitive way to get started with TensorFlow.

Some things to note :
* We enable eager at program startup using: ```tf.enable_eager_execution()```.
* Once we enable Eager with ```tf.enable_eager_execution()```, it cannot be turned off. To get back to graph mode, start a new Python session.

Before we get started with Eager, let's see what happens when we define a simple operation in graph mode :

In [2]:
import tensorflow as tf

print("Tensorflow Version ",tf.VERSION)
print("\n")
print(tf.add(1, 2))

Tensorflow Version  1.12.0


Tensor("Add_1:0", shape=(), dtype=int32)


This tells us that we are just building a computation graph with the above operation, and not actually executing anything. Let's see how Eager is different. 

In [ ]:
import os
os._exit(00)

We restart the Python kernel and start Eager execution. <b>This command will cause your kernel to die but this is okay since we are restarting.</b>

In [2]:
import tensorflow as tf

tf.enable_eager_execution()

In [3]:
tf.executing_eagerly() # check if eager execution is enable or not

True

In [4]:
print(tf.add(1, 2))

tf.Tensor(3, shape=(), dtype=int32)


Great! We just defined and executed an operation in TensorFlow immediately as it was called.

Eager execution works nicely with Numpy. Since numpy operations accept <i>tf.Tensor</i> arguments.

In [5]:
x = tf.constant([[1, 2], [3, 4]])
print(x)
print("\n")
print(type(x))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<class 'tensorflow.python.framework.ops.EagerTensor'>


In [6]:
y = tf.add(x, 1)
print(y)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [7]:
# Use numpy values
import numpy as np

z = np.multiply(x, y) # numpy takes tensors as an argument
print(z)
print("\n")
print(type(z))

[[ 2  6]
 [12 20]]


<class 'numpy.ndarray'>


In [8]:
# Obtain numpy value from a tensor
print(x.numpy())

[[1 2]
 [3 4]]


##### Dynamic Models

It can be built with Python flow control. 

In [9]:
a = tf.constant(12)
counter = 0
while not tf.equal(a, 1):
    if tf.equal(a % 2, 0):
        a = a / 2
    else:
        a = 3 * a + 1
    print(a)

tf.Tensor(6.0, shape=(), dtype=float64)
tf.Tensor(3.0, shape=(), dtype=float64)
tf.Tensor(10.0, shape=(), dtype=float64)
tf.Tensor(5.0, shape=(), dtype=float64)
tf.Tensor(16.0, shape=(), dtype=float64)
tf.Tensor(8.0, shape=(), dtype=float64)
tf.Tensor(4.0, shape=(), dtype=float64)
tf.Tensor(2.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)


### Now you see the advantage of using Eager execution. Try it yourself.