### One Hot Encoding

Today, we see the concept of <b>one hot encoding</b> in tensorflow. The term '<b>one hot</b>' is come from the electronics background where it means among all the bits only one bit is <i>high(1)</i> and other bits are <i>low(0)</i>. It's opposite '<b>one cold</b>' means among all the bits only one bit is <i>low(0)</i> and other bits are <i>high(1)</i>. 

But today we will focus on <b>tf.one_hot</b>.


<b>What is one hot encoding?</b> <br>
Let's take an example of most popular dataset i.e. Iris dataset in which we are having three different labels - <b>setosa, versicolor, and virginica</b>. Now we all know that computers only understand numerical data, we can't perform any mathematical computation on strings. So, we need to map our labels to some numerical values. This mapping process is known as <b>encoding</b>.<br>
The easiest way of encoding is:
* setosa --> 0
* versicolor --> 1
* virginica --> 2 <br>

we replace each label with it's mapped value. <br>
But, there is a problem in this method, what if the number of labels increases. Say, you have 30 unique labels, then you have to map all 30 of them. And it might also be possible that your ML model start taking these categorical values as integers and also perform numerical operations on it. A suitation may arises when you need to find out total number of setosa and versicolor, then what if it sum up all of them by identifying them as integer value. Therefore, this is not the best approach. So what should be need to do then. <br>
Well, the solution to this problem is <b>one-hot encoding</b> where we create <i>N</i> number of new features, where <i>N</i> is the total number of unique labels in the dataset. In our example of <i>Iris dataset</i> we have 3 unique labels (setosa, versicolor, and virginica), hence <b>N = 3</b>.

The way of <b>One Hot Encoding</b> is:
* setosa : [1, 0, 0]
* versicolor : [0, 1, 0]
* virginica : [0, 0, 1] <br>

Now, instead of having 0, 1, and 2 as 3 values, we are having an array of 3 values(similiar to <i>N</i> values). The index of the array is set to 1 for the relative flower and 0 for the rest of them. For example, in case of setosa we have 1 at first position only and in case of virginica we have 1 at third position only. This can be explained with a simple diagram :

|Labels|      |  |setosa|versicolor|virginica|
|---|    -----  |------|----------|---------|
|setosa|      |  | 1 | 0 | 0 |
|versicolor|  |  | 0 | 1 | 0 |
|virginica|   |  | 0 | 0 | 1 |

Now, you know about one-hot encoding to let's see some examples on it. <br>
In TensorFlow, for one-hot-encoding we use <b>tf.one_hot</b>. It's signature is <br>
<b>tf.one_hot(indices, depth, on_value, off_value, axis, dtype, name)</b><br>
where,<br>
* <b>indices</b> : A tensor of indices.
* <b>depth</b> : depth of one hot dimension.
* <b>on_value</b> : A scalar defining the value to fill in output when indices[j] = i. (default: 1)
* <b>off_value</b> : A scalar defining the value to fill in output when indices[j] != i. (default: 0)
* <b>axis</b> : the axis to fill. (default: -1)
* <b>dtype</b> : The data type of output tensor.
* <b>name</b> : A name of the operation. (optional)

#### 1. Simple example

In [2]:
# Import required libraries
import tensorflow as tf
import numpy as np

In [4]:
labels = [0, 1, 2]
result = tf.one_hot(indices= labels, depth= 3) # depth = N
print(result)

Tensor("one_hot:0", shape=(3, 3), dtype=float32)


In [5]:
with tf.Session():
    print(result.eval())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Now, you see how we optained the same result.<br>
We can also change the other parameters of <b>tf.one_hot</b>.

In [6]:
new_result = tf.one_hot(indices= labels, depth= 3, on_value= 5.0, off_value= 0.0, axis= -1)
with tf.Session():
    print(new_result.eval())

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


<b>on_value</b> replaces 1.0 with 5.0 and <b>off_value</b> remains 0.0 <br>

#### 2. Iris Dataset Example:

In [37]:
# load the dataset
from sklearn.datasets import load_iris
data = load_iris()
iris_labels = data.target
print(iris_labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Here, 0 represents setosa, 1 represents versicolor, and 2 represents virginica

In [38]:
# convert array to tensor
tensor = tf.convert_to_tensor(iris_labels, dtype=tf.int32)
print(tensor)

Tensor("Const_3:0", shape=(150,), dtype=int32)


Now tensor is created and we repeat the first example

In [39]:
final_result = tf.one_hot(indices= tensor, depth = 3)
with tf.Session():
    df = pd.DataFrame(data = final_result.eval(), columns = ["setosa", "versicolor", "virginica"])
    print(final_result.eval())

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

Now, we get the same result

In [40]:
df.head()

setosa  versicolor  virginica
0     1.0         0.0        0.0
1     1.0         0.0        0.0
2     1.0         0.0        0.0
3     1.0         0.0        0.0
4     1.0         0.0        0.0

In [41]:
# load iris data into the dataframe
iris_df = pd.DataFrame(data = data.data, columns= data.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [47]:
# combined both the dataframes
final_df = pd.concat([iris_df, df], axis= 1, join_axes=[iris_df.index])
final_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4               2.8                5.6               2.2   
133                6.3               2.8                5.1               1.5   
134                6.1               2.6                5.6               1.4   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4              

### Now, I am sure that you can do the one-hot encoding my your self.